Initial support for openapiv3
LucasPickering/slumber pull request #233
Opened 2024-05-25 14:53 UTC by AlisCode

## Description

Implementation of #106 .
Allows to import Slumber recipes from an OpenAPI specification.

## Known Risks

Not really applicable as this is a new feature, all stuff that is known to not work is clearly commented with a TODO.

Namely, it doesn't look like slumber supports : 
* Cookies
* Path parameters
* OAuth2
* OpenIDConnect

## QA

I added the classic `petstore` sample OpenAPI specification as a test. Feel free to import that and see if that works :)
There is one integration test that tests the feature as a whole, and then a few unit tests for the OpenAPI "reference resolving" module.   

## Checklist

- [x] Have you read `CONTRIBUTING.md` already?
- [x] Did you update `CHANGELOG.md`?
  - Only user-facing changes belong in the changelog. Internal changes such as refactors should only be included if they'll impact users, e.g. via performance improvement.
- [ ] Did you remove all TODOs?

-> I think I'd like to discuss a bit more before removing the TODOs and opening more issues, as these are not exactly small features :)

2024-05-27 22:04 UTC, LucasPickering requested changes
I haven't gone through it entirely, but this should be enough feedback to keep you busy until I have more time to test this.

2024-05-27 22:04 UTC, LucasPickering commented on src/collection/openapiv3/resolve.rs
> +impl<'a> TryFrom<&'a str> for OpenApiComponentReference<'a> {
`FromStr` here too

2024-05-27 22:04 UTC, LucasPickering commented on src/collection.rs
> +mod openapiv3;
Why is the module named `openapiv3` rather than `openapi`? Would you expect different versions of openapi to require an entirely different implementation?

2024-05-27 22:04 UTC, LucasPickering commented on src/collection/openapiv3/resolve.rs
> +impl<'a> TryFrom<&'a str> for OpenApiResolvableComponentKind {
Could this be `FromStr` instead of `TryFrom`? That is more explicit and clear.

2024-05-27 22:04 UTC, LucasPickering commented on src/template.rs
> +    }
Could you make this a derived `Default` impl instead please?

2024-05-27 22:04 UTC, LucasPickering commented on src/collection/openapiv3/mod.rs
I prefer using the style `src/../x.rs` as opposed to `src/../x/mod.rs` because it makes files easier to find by name. Could you rename this please?

2024-05-27 22:04 UTC, LucasPickering commented on test_data/openapiv3_petstore.yml
> +    # post:
Why are these commented out?

2024-05-27 22:04 UTC, LucasPickering commented on src/collection/openapiv3/mod.rs
> +        dbg!(&expected);
```suggestion
```

2024-05-27 22:04 UTC, LucasPickering commented on src/collection/openapiv3/mod.rs
> +        dbg!(&imported);
```suggestion
```

2024-05-27 22:04 UTC, LucasPickering commented on src/collection/openapiv3/mod.rs
> +                // if the name field is "Accept", "Content-Type" or "Authorization", the parameter definition SHALL be ignored.
Why?

2024-05-27 22:04 UTC, LucasPickering commented on src/collection/openapiv3/mod.rs
> +        for (path_name, item) in paths.paths {
The length of this function and the indentation makes it very hard to follow. Could you please break this apart into helper functions?

2024-05-27 22:04 UTC, LucasPickering commented on src/collection/openapiv3/mod.rs
> +            "Error opening OpenAPI v3 (JSON) collection file {openapiv3_specification_file:?}"
There are a lot of long string literals that overflow the max line length, could you please wrap them to fit?

2024-05-27 22:04 UTC, LucasPickering commented on src/collection/openapiv3/mod.rs
> +                        // maintain. Let's grab the first tag instead, and that will be our folder
I think we should print a warning here if there are additional tags that aren't being used, so the user knows they're losing something.

2024-05-27 22:04 UTC, LucasPickering commented on src/collection/openapiv3/mod.rs
> +                            }
This would be more clear if you used [or_insert_with](https://docs.rs/indexmap/latest/indexmap/map/enum.Entry.html#method.or_insert_with) instead of a match

2024-05-27 22:04 UTC, LucasPickering commented on src/collection/openapiv3/mod.rs
> +                    try_add_recipe_for_method(path_item.trace, Method::Trace)?;
I think it'd be better to do something like this:

```
for method in Method::iter() {
    try_add_recipe_for_method(get_operation(method), method)?;
}
```

Then define `get_operation` to access the correct field for each method. I think this is better because it means we can't forget any single method since we're iterating over all of them.

2024-05-27 22:04 UTC, LucasPickering commented on src/collection/openapiv3/mod.rs
> +                    ));
```suggestion
                    bail!("Could not resolve reference to {reference}");
```

2024-05-27 22:04 UTC, LucasPickering commented on src/collection/openapiv3/mod.rs
> +        let mut tag_folders: IndexMap<String, Folder> = IndexMap::default();
What's the advantage of building this map up separately, then inserting into `recipes` later, as opposed to just inserting into `recipes` directly?

2024-05-27 22:04 UTC, LucasPickering commented on src/collection/openapiv3/mod.rs
> +        let mut profiles = IndexMap::default();
Could you change this to something like this please?

```
let profiles = servers.into_iter().map(|server| ...).try_collect()?;
```

This has a few advantages:
- It's immediately clear to the reader that servers:profiles is a 1:1 relationship
- `profiles` doesn't need to be `mut`, which means we know for sure it's not changed after it's created
- The compiler can easily pre-allocate the size for the new map because it knows it's the same size as the old one

2024-05-27 22:04 UTC, LucasPickering commented on src/collection/openapiv3/mod.rs
> +                        Template::try_from(value.clone()).context(format!(
None of the strings in the OpenAPI collection should be parsed as a template. If it looks like Slumber template syntax that's purely coincidental. Instead, it should use `Template::dangerous` (to be replaced by `Template::escaped` eventually).

2024-05-27 22:04 UTC, LucasPickering commented on src/collection/openapiv3/mod.rs
> +            let mut data = IndexMap::default();
Same as above, could you please use iterator syntax to generate this instead?

2024-05-27 22:04 UTC, LucasPickering commented on src/collection/openapiv3/mod.rs
> +            }
We could support these by mapping the path param to a template key, e.g. `/pet/{petId}` -> `/pet/{{petId}}`. What do you think? We would then probably want to insert `petId` (with an empty value?) into each profile

2024-05-28 12:23 UTC, AlisCode commented on src/collection/openapiv3/mod.rs
> +                // if the name field is "Accept", "Content-Type" or "Authorization", the parameter definition SHALL be ignored.
This is from the Open API specs : https://spec.openapis.org/oas/v3.0.3#fixed-fields-9

2024-06-18 01:14 UTC, LucasPickering commented
@AlisCode Do you intend to keep working on this? If not I can take it over

2024-06-18 19:44 UTC, AlisCode commented
Hi @LucasPickering, sorry I lost the focus on this. Feel free to take it from there. I'd be glad to review the code when you're done!

2024-07-02 22:27 UTC, LucasPickering approved these changes

2024-07-02 22:30 UTC, merged

2024-07-02 22:31 UTC, LucasPickering commented
@AlisCode Thanks for your work on this! I was pretty slow finishing it up but finally got it done. I'm sure there's lots of gaps in the transformation still but at least we have something to build off of now.