add-select: [tui/cli] prompting support for select chainsource
LucasPickering/slumber pull request #360
Opened 2024-09-01 21:15 UTC by anussel5559

## Description

Implements full prompting support for `select` chainsource in the TUI and CLI

Second phase of implementation for [issue#352](https://github.com/LucasPickering/slumber/issues/352)

## Known Risks

None

## QA

TUI behaves as expected:

https://github.com/user-attachments/assets/0f8e6f0d-0161-4e2b-b3b5-554abc51724c

CLI behaves as expected:

https://github.com/user-attachments/assets/31103a0d-0e40-4e97-9671-e3e2700a3564

## Checklist

- [X] Have you read `CONTRIBUTING.md` already?
- [ ] Did you update `CHANGELOG.md`?
  - Only user-facing changes belong in the changelog. Internal changes such as refactors should only be included if they'll impact users, e.g. via performance improvement.
- [X] Did you remove all TODOs?
  - If there are unresolved issues, please open a follow-on issue and link to it in a comment so future work can be tracked

2024-09-01 22:57 UTC, LucasPickering requested changes
Nice work, just a couple small things

2024-09-01 22:57 UTC, LucasPickering commented on crates/slumber_tui/src/view/component/misc.rs
> +        self.title.clone().into()
```suggestion
        self.title.as_str().into()
```
Should work without cloning

2024-09-01 22:57 UTC, LucasPickering commented on crates/slumber_tui/src/view/component/misc.rs
> +            Constraint::Length(options.len() as u16),
```suggestion
            Constraint::Length(options.len().min(20) as u16),
```
I would put a cap on this, so it doesn't blow out the screen if the list is very long. 20 will still overflow smaller screens, but generally should be fine.

2024-09-01 22:57 UTC, LucasPickering commented on crates/slumber_cli/src/commands/request.rs
> +            select.channel.respond(select.options[value].clone());
```suggestion
            select.channel.respond(select.options.swap_remove(value));
```
We can avoid the clone since we're going to trash `select.options` after this anyway.

2024-09-02 00:45 UTC, anussel5559 commented on crates/slumber_cli/src/commands/request.rs
> +            select.channel.respond(select.options[value].clone());
ah, super clever! I was not aware of that method (still pretty early on in my rust journey).

2024-09-02 01:11 UTC, LucasPickering approved these changes
Nice job :)

2024-09-02 01:13 UTC, merged